version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_NAME:-dates}
      MYSQL_USER: ${DB_USERNAME:-dates}
      MYSQL_PASSWORD: ${DB_PASSWORD:-123456}
    volumes:
      - database_data:/var/lib/mysql
    ports:
      - ${DB_PORT:-13306}:3306

  redis:
    image: redis:latest
    command: --appendonly yes --requirepass ${REDIS_PASSWORD:-123456}
    volumes:
      - redis_data:/data
    ports:
      - ${REDIS_PORT:-16379}:6379

  media_manager:
    build:
      context: ./media_manager
      args:
        APPLICATION_NAME: ${APPLICATION_NAME:-Dates}

        DB_HOST: ${DB_HOST:-host.docker.internal}
        DB_PORT: ${DB_PORT:-13306}
        DB_NAME: ${DB_NAME:-dates}
        DB_USERNAME: ${DB_USERNAME:-dates}
        DB_PASSWORD: ${DB_PASSWORD:-123456}

        JWT_KEY: ${JWT_KEY:-up65tUz!3zLT7y*Xaok!ZFJCQnCAmb8M8h3Dy%E6swTXRt&TjeygD8zKdRb9yS}

        MAIL_USERNAME: ${MAIL_USERNAME}
        MAIL_PASSWORD: ${MAIL_PASSWORD}

        REDIS_HOST: ${REDIS_HOST:-redis}
        REDIS_PORT: ${REDIS_PORT:-16379}
        REDIS_PASSWORD: ${REDIS_PASSWORD:-123456}

        DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-fa}
        DEFAULT_COUNTRY: ${DEFAULT_COUNTRY:-IR}
    ports:
      - '${MEDIA_MANAGER_PORT:-8080}:8080'
    depends_on:
      - mysql
      - redis
    volumes:
      - .:/media_manager

volumes:
  database_data:
  redis_data:
